// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecztdooxfatgrupvoeas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjenRkb294ZmF0Z3J1cHZvZWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3MzAwODgsImV4cCI6MjA4NjMwNjA4OH0.0xtj3OUg1lAUOMJTXG3trI-z7a_GdoZzqFOTCpTltg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});